aws_region    = "us-east-1"
ami           = "ami-0eb5c571bf15422ac"
vpc_id        = "vpc-0a94db89344c16694"
instance_type = "t2.micro"
key_name      = "jenkins-key"
subnet_id     = "subnet-0ee4a88e854808dbb"
common_tags = {
  "AssetID"       = "2560"
  "AssetName"     = "Insfrastructure"
  "Teams"         = "DEL"
  "Environment"   = "tia"
  "Project"       = "alpha"
  "CreateBy"      = "Terraform"
  "cloudProvider" = "aws"
}
